/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mae.vue;

import java.time.LocalDate;
import com.mae.vue.InterfaceAgent;
import com.mae.controller.ArticleController;
import com.mae.controller.ImportExcelController;

import java.time.format.DateTimeFormatter;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author kobie
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    public static void afficherDateDuJour() {
        LocalDate dateAujourdhui = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String dateFormatee = dateAujourdhui.format(formatter);
        dateJour.setText(dateFormatee);
    }

    public static void afficherHeure() {
        ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);

        Runnable afficherHeure = () -> {
            LocalTime heureActuelle = LocalTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
            heureJour.setText(heureActuelle.format(formatter));
            // System.out.println("Heure actuelle : " + heureActuelle.format(formatter));
        };

        // Exécute la tâche toutes les secondes
        scheduler.scheduleAtFixedRate(afficherHeure, 0, 1, TimeUnit.SECONDS);
    }
    
     //Méthode pour exécuter l'import d'un fichier excel
    public static void importerExcel() {
        ImportExcelController.importFichierExcelAgent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panneauDeBase = new javax.swing.JPanel();
        panneauMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateJour = new javax.swing.JLabel();
        heureJour = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panneauEntete = new javax.swing.JPanel();
        btn_moncompte = new javax.swing.JButton();
        btn_deconnexion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panneauBureau = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menu_fichier = new javax.swing.JMenu();
        menu_moncompte = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menu_deconnexion = new javax.swing.JMenuItem();
        menu_parametre = new javax.swing.JMenu();
        menu_structure = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menu_catechelle = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        menu_emploi = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        menu_fonction = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        menu_ministere = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        menu_agent = new javax.swing.JMenu();
        menu_agent_fonct = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        menu_agent_contrac = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        menu_agent_amba = new javax.swing.JMenuItem();
        menu_budget = new javax.swing.JMenu();
        menu_creerbudget = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menu_article = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        menu__stattistiques = new javax.swing.JMenu();
        menu_paramavance = new javax.swing.JMenu();
        menu_importagent = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        menu_utilisateurs = new javax.swing.JMenu();
        menu_profils = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        menu_user = new javax.swing.JMenuItem();
        menu_aide = new javax.swing.JMenu();
        userConnected = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Deper - Tableau de bord principal");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panneauDeBase.setBackground(new java.awt.Color(255, 255, 255));
        panneauDeBase.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        panneauMenu.setBackground(new java.awt.Color(0, 102, 51));
        panneauMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        panneauMenu.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MAEC-RBE");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Date : ");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Heure :");

        dateJour.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        dateJour.setForeground(new java.awt.Color(255, 255, 255));

        heureJour.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        heureJour.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Revenir à la page d'acceuil");
        jButton1.setToolTipText("Revenir à la page d'acceuil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panneauMenuLayout = new javax.swing.GroupLayout(panneauMenu);
        panneauMenu.setLayout(panneauMenuLayout);
        panneauMenuLayout.setHorizontalGroup(
            panneauMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(panneauMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panneauMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panneauMenuLayout.createSequentialGroup()
                        .addGroup(panneauMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panneauMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panneauMenuLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(dateJour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panneauMenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heureJour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        panneauMenuLayout.setVerticalGroup(
            panneauMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panneauMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateJour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panneauMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(heureJour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        panneauEntete.setBackground(new java.awt.Color(255, 255, 255));
        panneauEntete.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 0, 0)));

        btn_moncompte.setBackground(new java.awt.Color(0, 102, 0));
        btn_moncompte.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btn_moncompte.setForeground(new java.awt.Color(255, 255, 255));
        btn_moncompte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/account.png"))); // NOI18N
        btn_moncompte.setText("Mon compte");
        btn_moncompte.setToolTipText("Mon compte");
        btn_moncompte.setBorder(null);
        btn_moncompte.setMaximumSize(new java.awt.Dimension(68, 22));
        btn_moncompte.setMinimumSize(new java.awt.Dimension(68, 22));
        btn_moncompte.setPreferredSize(new java.awt.Dimension(68, 22));

        btn_deconnexion.setBackground(new java.awt.Color(204, 0, 0));
        btn_deconnexion.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btn_deconnexion.setForeground(new java.awt.Color(255, 255, 255));
        btn_deconnexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se-deconnecter.png"))); // NOI18N
        btn_deconnexion.setText("Se déconnecter");
        btn_deconnexion.setToolTipText("Se déconnecter");
        btn_deconnexion.setBorder(null);
        btn_deconnexion.setMaximumSize(new java.awt.Dimension(68, 22));
        btn_deconnexion.setMinimumSize(new java.awt.Dimension(68, 22));
        btn_deconnexion.setPreferredSize(new java.awt.Dimension(68, 22));
        btn_deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deconnexionActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/armoirie2.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 0, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Gestion des dépenses du personnel");

        javax.swing.GroupLayout panneauEnteteLayout = new javax.swing.GroupLayout(panneauEntete);
        panneauEntete.setLayout(panneauEnteteLayout);
        panneauEnteteLayout.setHorizontalGroup(
            panneauEnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauEnteteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 468, Short.MAX_VALUE)
                .addGroup(panneauEnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_deconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_moncompte, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        panneauEnteteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_deconnexion, btn_moncompte});

        panneauEnteteLayout.setVerticalGroup(
            panneauEnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauEnteteLayout.createSequentialGroup()
                .addGroup(panneauEnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panneauEnteteLayout.createSequentialGroup()
                        .addGroup(panneauEnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panneauEnteteLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel3))
                            .addGroup(panneauEnteteLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btn_moncompte, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_deconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panneauEnteteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_deconnexion, btn_moncompte});

        panneauBureau.setBackground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout panneauBureauLayout = new javax.swing.GroupLayout(panneauBureau);
        panneauBureau.setLayout(panneauBureauLayout);
        panneauBureauLayout.setHorizontalGroup(
            panneauBureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1903, Short.MAX_VALUE)
        );
        panneauBureauLayout.setVerticalGroup(
            panneauBureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panneauDeBaseLayout = new javax.swing.GroupLayout(panneauDeBase);
        panneauDeBase.setLayout(panneauDeBaseLayout);
        panneauDeBaseLayout.setHorizontalGroup(
            panneauDeBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauDeBaseLayout.createSequentialGroup()
                .addComponent(panneauMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panneauEntete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panneauBureau)
        );
        panneauDeBaseLayout.setVerticalGroup(
            panneauDeBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauDeBaseLayout.createSequentialGroup()
                .addGroup(panneauDeBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panneauEntete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panneauMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panneauBureau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuBar.setBackground(new java.awt.Color(204, 0, 0));
        menuBar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 204, 0)));
        menuBar.setPreferredSize(new java.awt.Dimension(103, 35));

        menu_fichier.setBackground(new java.awt.Color(255, 204, 0));
        menu_fichier.setForeground(new java.awt.Color(255, 255, 255));
        menu_fichier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fichier.png"))); // NOI18N
        menu_fichier.setText("Fichier");
        menu_fichier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menu_moncompte.setBackground(new java.awt.Color(255, 204, 0));
        menu_moncompte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menu_moncompte.setText("Mon compte");
        menu_moncompte.setToolTipText("Mon compte");
        menu_fichier.add(menu_moncompte);

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        menu_fichier.add(jSeparator3);

        menu_deconnexion.setBackground(new java.awt.Color(255, 204, 0));
        menu_deconnexion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menu_deconnexion.setText("Se déconnecter");
        menu_deconnexion.setToolTipText("Se déconnecter");
        menu_deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_deconnexionActionPerformed(evt);
            }
        });
        menu_fichier.add(menu_deconnexion);

        menuBar.add(menu_fichier);

        menu_parametre.setBackground(new java.awt.Color(255, 204, 0));
        menu_parametre.setForeground(new java.awt.Color(255, 255, 255));
        menu_parametre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parametre.png"))); // NOI18N
        menu_parametre.setText("Paramètres");
        menu_parametre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menu_structure.setBackground(new java.awt.Color(255, 204, 0));
        menu_structure.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menu_structure.setText("Gestion des structures du ministère");
        menu_structure.setToolTipText("Gestion des structures du ministère");
        menu_structure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_structureActionPerformed(evt);
            }
        });
        menu_parametre.add(menu_structure);

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        menu_parametre.add(jSeparator2);

        menu_catechelle.setBackground(new java.awt.Color(255, 204, 0));
        menu_catechelle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menu_catechelle.setText("Gestion des catégories/échelles");
        menu_catechelle.setToolTipText("Gestion des catégories/échelles");
        menu_catechelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_catechelleActionPerformed(evt);
            }
        });
        menu_parametre.add(menu_catechelle);

        jSeparator11.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        menu_parametre.add(jSeparator11);

        menu_emploi.setBackground(new java.awt.Color(255, 204, 0));
        menu_emploi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menu_emploi.setText("Gestion des emplois");
        menu_emploi.setToolTipText("Gestion des emplois");
        menu_emploi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_emploiActionPerformed(evt);
            }
        });
        menu_parametre.add(menu_emploi);

        jSeparator14.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));
        menu_parametre.add(jSeparator14);

        menu_fonction.setBackground(new java.awt.Color(255, 204, 0));
        menu_fonction.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menu_fonction.setText("Gestion des fonctions");
        menu_fonction.setToolTipText("Gestion des fonctions");
        menu_fonction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_fonctionActionPerformed(evt);
            }
        });
        menu_parametre.add(menu_fonction);

        jSeparator13.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));
        menu_parametre.add(jSeparator13);

        menu_ministere.setBackground(new java.awt.Color(255, 204, 0));
        menu_ministere.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menu_ministere.setText("Gestion des ministères");
        menu_ministere.setToolTipText("Gestion des ministères");
        menu_ministere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ministereActionPerformed(evt);
            }
        });
        menu_parametre.add(menu_ministere);

        jSeparator12.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        menu_parametre.add(jSeparator12);

        menu_agent.setBackground(new java.awt.Color(255, 204, 0));
        menu_agent.setText("Gestion des agents");
        menu_agent.setToolTipText("Gestion des agents");
        menu_agent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menu_agent_fonct.setBackground(new java.awt.Color(255, 204, 0));
        menu_agent_fonct.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menu_agent_fonct.setText("Gestion des agents fonctionnaires");
        menu_agent_fonct.setToolTipText("Gestion des agents fonctionnaires");
        menu_agent_fonct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_agent_fonctActionPerformed(evt);
            }
        });
        menu_agent.add(menu_agent_fonct);

        jSeparator18.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));
        menu_agent.add(jSeparator18);

        menu_agent_contrac.setBackground(new java.awt.Color(255, 204, 0));
        menu_agent_contrac.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menu_agent_contrac.setText("Gestion des agents contractuels");
        menu_agent_contrac.setToolTipText("Gestion des agents contractuels");
        menu_agent_contrac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_agent_contracActionPerformed(evt);
            }
        });
        menu_agent.add(menu_agent_contrac);

        jSeparator19.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator19.setForeground(new java.awt.Color(255, 255, 255));
        menu_agent.add(jSeparator19);

        menu_agent_amba.setBackground(new java.awt.Color(255, 204, 0));
        menu_agent_amba.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menu_agent_amba.setText("Gestion des ambassadeurs & consuls");
        menu_agent_amba.setToolTipText("Gestion des ambassadeurs & consuls");
        menu_agent_amba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_agent_ambaActionPerformed(evt);
            }
        });
        menu_agent.add(menu_agent_amba);

        menu_parametre.add(menu_agent);

        menuBar.add(menu_parametre);

        menu_budget.setBackground(new java.awt.Color(255, 204, 0));
        menu_budget.setForeground(new java.awt.Color(255, 255, 255));
        menu_budget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/budget.png"))); // NOI18N
        menu_budget.setText("Budget");
        menu_budget.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menu_creerbudget.setBackground(new java.awt.Color(255, 204, 0));
        menu_creerbudget.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menu_creerbudget.setText("Créer un budget");
        menu_creerbudget.setToolTipText("Créer un budget");
        menu_creerbudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_creerbudgetActionPerformed(evt);
            }
        });
        menu_budget.add(menu_creerbudget);

        jSeparator10.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        menu_budget.add(jSeparator10);

        jMenuItem3.setBackground(new java.awt.Color(255, 204, 0));
        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem3.setText("Programme");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu_budget.add(jMenuItem3);

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        menu_budget.add(jSeparator5);

        jMenuItem4.setBackground(new java.awt.Color(255, 204, 0));
        jMenuItem4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem4.setText("Action");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menu_budget.add(jMenuItem4);

        jSeparator6.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        menu_budget.add(jSeparator6);

        jMenuItem5.setBackground(new java.awt.Color(255, 204, 0));
        jMenuItem5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem5.setText("Chapritre");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menu_budget.add(jMenuItem5);

        jSeparator7.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        menu_budget.add(jSeparator7);

        jMenuItem6.setBackground(new java.awt.Color(255, 204, 0));
        jMenuItem6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem6.setText("Activité");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menu_budget.add(jMenuItem6);

        jSeparator8.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        menu_budget.add(jSeparator8);

        menu_article.setBackground(new java.awt.Color(255, 204, 0));
        menu_article.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menu_article.setText("Article");
        menu_article.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_articleActionPerformed(evt);
            }
        });
        menu_budget.add(menu_article);

        jSeparator9.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        menu_budget.add(jSeparator9);

        jMenuItem8.setBackground(new java.awt.Color(255, 204, 0));
        jMenuItem8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem8.setText("Paragraphe");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menu_budget.add(jMenuItem8);

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        menu_budget.add(jSeparator4);

        jMenuItem2.setBackground(new java.awt.Color(255, 204, 0));
        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem2.setText("Editer les lignes du budget");
        jMenuItem2.setToolTipText("Editer les lignes du  budget");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_budget.add(jMenuItem2);

        menuBar.add(menu_budget);

        menu__stattistiques.setBackground(new java.awt.Color(255, 204, 0));
        menu__stattistiques.setForeground(new java.awt.Color(255, 255, 255));
        menu__stattistiques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/statistiques.png"))); // NOI18N
        menu__stattistiques.setText("Statistiques");
        menu__stattistiques.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuBar.add(menu__stattistiques);

        menu_paramavance.setBackground(new java.awt.Color(255, 204, 0));
        menu_paramavance.setForeground(new java.awt.Color(255, 255, 255));
        menu_paramavance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parametres.png"))); // NOI18N
        menu_paramavance.setText("Paramètres avancés");
        menu_paramavance.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menu_importagent.setBackground(new java.awt.Color(255, 204, 0));
        menu_importagent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menu_importagent.setText("Importer les agents");
        menu_importagent.setToolTipText("Importer les agents");
        menu_importagent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_importagentActionPerformed(evt);
            }
        });
        menu_paramavance.add(menu_importagent);

        jSeparator15.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));
        menu_paramavance.add(jSeparator15);

        menu_utilisateurs.setBackground(new java.awt.Color(255, 204, 0));
        menu_utilisateurs.setText("Utilisateurs");
        menu_utilisateurs.setToolTipText("Utilisateurs");
        menu_utilisateurs.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menu_profils.setBackground(new java.awt.Color(255, 204, 0));
        menu_profils.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menu_profils.setText("Profils");
        menu_profils.setToolTipText("Profils");
        menu_profils.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_profilsActionPerformed(evt);
            }
        });
        menu_utilisateurs.add(menu_profils);

        jSeparator17.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));
        menu_utilisateurs.add(jSeparator17);

        menu_user.setBackground(new java.awt.Color(255, 204, 0));
        menu_user.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menu_user.setText("Utilisateurs");
        menu_user.setToolTipText("Utilisateurs");
        menu_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_userActionPerformed(evt);
            }
        });
        menu_utilisateurs.add(menu_user);

        menu_paramavance.add(menu_utilisateurs);

        menuBar.add(menu_paramavance);

        menu_aide.setBackground(new java.awt.Color(255, 204, 0));
        menu_aide.setForeground(new java.awt.Color(255, 255, 255));
        menu_aide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question.png"))); // NOI18N
        menu_aide.setText("Aide");
        menu_aide.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuBar.add(menu_aide);

        userConnected.setBackground(new java.awt.Color(0, 102, 51));
        userConnected.setForeground(new java.awt.Color(255, 204, 0));
        userConnected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilisateur.png"))); // NOI18N
        userConnected.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userConnected.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        menuBar.add(userConnected);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panneauDeBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panneauDeBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        afficherDateDuJour();
        afficherHeure();
        menuBar.add(Box.createHorizontalGlue());
        
       
        
    }//GEN-LAST:event_formWindowActivated

    private void menu_structureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_structureActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceStructure amb = new InterfaceStructure();
        amb.setSize(1900, 760);
        panneauBureau.add(amb).setVisible(true);
    }//GEN-LAST:event_menu_structureActionPerformed

    private void menu_deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_deconnexionActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceArticle art = new InterfaceArticle();
        art.setSize(1900, 760);
        panneauBureau.add(art).setVisible(true);
    }//GEN-LAST:event_menu_deconnexionActionPerformed

    private void menu_articleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_articleActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceArticle art = new InterfaceArticle();
        art.setSize(1900, 760);
        panneauBureau.add(art).setVisible(true);
    }//GEN-LAST:event_menu_articleActionPerformed

    private void menu_creerbudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_creerbudgetActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceBudget budg = new InterfaceBudget();
        budg.setSize(1900, 760);
        panneauBureau.add(budg).setVisible(true);
    }//GEN-LAST:event_menu_creerbudgetActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceProgramme prog = new InterfaceProgramme();
        prog.setSize(1900, 760);
        panneauBureau.add(prog).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceAction act = new InterfaceAction();
        act.setSize(1900, 760);
        panneauBureau.add(act).setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceChapitre chap = new InterfaceChapitre();
        chap.setSize(1900, 760);
        panneauBureau.add(chap).setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceActivite activi = new InterfaceActivite();
        activi.setSize(1900, 760);
        panneauBureau.add(activi).setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceParagraphe parag = new InterfaceParagraphe();
        parag.setSize(1900, 760);
        panneauBureau.add(parag).setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceLigne ligne = new InterfaceLigne();
        ligne.setSize(1900, 760);
        panneauBureau.add(ligne).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menu_agent_fonctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_agent_fonctActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceAgent age = new InterfaceAgent();
        age.setSize(1900, 760);
        panneauBureau.add(age).setVisible(true);
    }//GEN-LAST:event_menu_agent_fonctActionPerformed

    private void menu_catechelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_catechelleActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceCategorieEchelle catech = new InterfaceCategorieEchelle();
        catech.setSize(1900, 760);
        panneauBureau.add(catech).setVisible(true);
    }//GEN-LAST:event_menu_catechelleActionPerformed

    private void menu_ministereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ministereActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceMinistere min = new InterfaceMinistere();
        min.setSize(1900, 760);
        panneauBureau.add(min).setVisible(true);
    }//GEN-LAST:event_menu_ministereActionPerformed

    private void menu_emploiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_emploiActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceEmploi empl = new InterfaceEmploi();
        empl.setSize(1900, 760);
        panneauBureau.add(empl).setVisible(true);
    }//GEN-LAST:event_menu_emploiActionPerformed

    private void menu_fonctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_fonctionActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceFonction fonct = new InterfaceFonction();
        fonct.setSize(1900, 760);
        panneauBureau.add(fonct).setVisible(true);
    }//GEN-LAST:event_menu_fonctionActionPerformed

    private void menu_importagentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_importagentActionPerformed
        // TODO add your handling code here:
        importerExcel();
    }//GEN-LAST:event_menu_importagentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceAcceuil acc = new InterfaceAcceuil();
        acc.setSize(1900, 760);
        panneauBureau.add(acc).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         panneauBureau.removeAll();
        InterfaceAcceuil acc = new InterfaceAcceuil();
        acc.setSize(1900, 760);
        panneauBureau.add(acc).setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void menu_agent_contracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_agent_contracActionPerformed
        // TODO add your handling code here:
       panneauBureau.removeAll();
        InterfaceAgentContractuel aegentContract = new InterfaceAgentContractuel();
        aegentContract.setSize(1900, 760);
        panneauBureau.add(aegentContract).setVisible(true); 
        
    }//GEN-LAST:event_menu_agent_contracActionPerformed

    private void menu_agent_ambaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_agent_ambaActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceAmbassadeurConsul amba = new InterfaceAmbassadeurConsul();
        amba.setSize(1900, 760);
        panneauBureau.add(amba).setVisible(true); 
    }//GEN-LAST:event_menu_agent_ambaActionPerformed

    private void menu_profilsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_profilsActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceProfil prof = new InterfaceProfil();
        prof.setSize(1900, 760);
        panneauBureau.add(prof).setVisible(true);

    }//GEN-LAST:event_menu_profilsActionPerformed

    private void menu_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_userActionPerformed
        // TODO add your handling code here:
        panneauBureau.removeAll();
        InterfaceUser user = new InterfaceUser();
        user.setSize(1900, 760);
        panneauBureau.add(user).setVisible(true);
    }//GEN-LAST:event_menu_userActionPerformed

    private void btn_deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deconnexionActionPerformed
        // TODO add your handling code here:
        int rep = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment fermer l'application", "Fermeture", JOptionPane.YES_NO_OPTION);
        if (rep == JOptionPane.YES_OPTION) {
            this.dispose();
            InterfaceConnexion ic = new InterfaceConnexion();
            ic.setIconImage(new ImageIcon("C:/deper/src/main/resources/iconapp.png").getImage());
            ic.setVisible(true);
        }
    }//GEN-LAST:event_btn_deconnexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
                new MenuPrincipal().setExtendedState(MAXIMIZED_BOTH);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deconnexion;
    private javax.swing.JButton btn_moncompte;
    public static javax.swing.JLabel dateJour;
    public static javax.swing.JLabel heureJour;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    public static javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenu menu__stattistiques;
    public static javax.swing.JMenu menu_agent;
    private javax.swing.JMenuItem menu_agent_amba;
    private javax.swing.JMenuItem menu_agent_contrac;
    private javax.swing.JMenuItem menu_agent_fonct;
    private javax.swing.JMenu menu_aide;
    private javax.swing.JMenuItem menu_article;
    public static javax.swing.JMenu menu_budget;
    public static javax.swing.JMenuItem menu_catechelle;
    private javax.swing.JMenuItem menu_creerbudget;
    private javax.swing.JMenuItem menu_deconnexion;
    public static javax.swing.JMenuItem menu_emploi;
    private javax.swing.JMenu menu_fichier;
    public static javax.swing.JMenuItem menu_fonction;
    private javax.swing.JMenuItem menu_importagent;
    public static javax.swing.JMenuItem menu_ministere;
    private javax.swing.JMenuItem menu_moncompte;
    public static javax.swing.JMenu menu_paramavance;
    private javax.swing.JMenu menu_parametre;
    private javax.swing.JMenuItem menu_profils;
    public static javax.swing.JMenuItem menu_structure;
    private javax.swing.JMenuItem menu_user;
    private javax.swing.JMenu menu_utilisateurs;
    private javax.swing.JDesktopPane panneauBureau;
    private javax.swing.JPanel panneauDeBase;
    private javax.swing.JPanel panneauEntete;
    private javax.swing.JPanel panneauMenu;
    public static javax.swing.JMenu userConnected;
    // End of variables declaration//GEN-END:variables
}
